### ISSUE TITLE
Unaligned pointer causing UB

### ISSUE THREAD

**Issue by JelleZijlstra** [fuzziqersoftware/sharedstructures#3]
At this line: https://github.com/fuzziqersoftware/sharedstructures/blob/bebf5398cdd4e0ad682dbf69c20aed403ff5139a/src/PythonModule.cc#L163-L164
we create an unaligned `wchar_t*` pointer, because we add 1 byte to a valid pointer. As I understand it, this is undefined behavior, because C and C++ require all pointers to be aligned to their size. I ran into this after I compiled a new Python binary, and for whatever reason gcc (7.5.0) started emitting code that depends on the pointer being properly aligned. I spent some quality time with gdb and tracked it down to the unaligned pointer generated by sharedstructures.

It's not immediately obvious to me how to fix the bug. Does sharedstructures rely on having pointers offset by 1 byte?

**Comment by fuzziqersoftware** [comment]
In this case, we're using the +1 to skip the format byte for the stored value. This is the only encoding where pointer alignment should matter, though I haven't tested the marshalled-object case extensively (it works on my machine). b3d64be0 should fix the Unicode string case - let me know if it still doesn't work.

**Comment by JelleZijlstra** [comment]
Thanks! I'll try it out tomorrow.

**Comment by JelleZijlstra** [comment]
The fix is deployed with no more segfaults. Thanks for your help!
